FROM oven/bun:1 AS base
WORKDIR /app

FROM base AS install
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM install AS run

COPY . .
CMD ["bunx", "@tailwindcss/cli", "-i", "./tailwind.css", "-o", "./assets/tailwind.css", "--watch"]
