[package]
name = "uid"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ulid = "=1.2.1"

serde.workspace = true

[lints]
workspace = true
