[package]
name = "logic"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
enum-table.workspace = true
serde.workspace = true

[lints]
workspace = true
