[package]
name = "net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
uid.workspace = true
logic.workspace = true

serde.workspace = true
serde_json.workspace = true
chrono.workspace = true

[lints]
workspace = true
